### ISSUE TITLE
Have you tested the file size?

### ISSUE THREAD

**Issue by kylewetton** [vireshshah/js-user-country#1]
I'm getting 500Kb from this module alone even after its packed. Is there a database of all countries its reading or something?

**Comment by vireshshah** [comment]
Thanks for reaching out. This library depends on momentjs timezone and unfortunately it's 1.34Mb unpacked version. Will see, if I can reduce the size somehow.

**Comment by kylewetton** [comment]
Fair call, I traced the dependency and noticed it was momentjs
